<?php

namespace Fer\AppDomain\Repository;

use Doctrine\ORM\EntityRepository;
use Fer\AppDomain\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository implements ItemRepositoryInterface
{
    public function save(Item $item) {
        $this->getEntityManager()->persist($item);
        $this->getEntityManager()->flush();
    }

    public function delete(Item $item){
        $this->getEntityManager()->remove($item);
        $this->getEntityManager()->flush();
    }
}
