<?php
/**
 * Created by PhpStorm.
 * User: fernando
 * Date: 03/03/14
 * Time: 20:56
 */
namespace Fer\AppDomain\Repository;

use Doctrine\DBAL\LockMode;
use Fer\AppDomain\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface ItemRepositoryInterface
{
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id The identifier.
     * @param int $lockMode The lock mode.
     * @param int|null $lockVersion The lock version.
     *
     * @return object|null The entity instance or NULL if the entity can not be found.
     */
    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null);

    public function delete(Item $item);

    /**
     * Finds all entities in the repository.
     *
     * @return array The entities.
     */
    public function findAll();

    public function save(Item $item);
}